services:
    dev-env:
        build:
            context: .
        environment:
            - YDB_ANONYMOUS_CREDENTIALS=1
            - ITGRAM_ENDPOINT=grpc://ydb:2136
            - ITGRAM_DATABASE=/local
            - ITGRAM_LOGLEVEL=info
        volumes:
            - ..:/workspace:cached
            - ~/.ssh:/home/dev/.ssh

    ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
            - 2135:2135
            - 2136:2136
            - 8765:8765
        environment:
            - YDB_DEFAULT_LOG_LEVEL=NOTICE
            - GRPC_TLS_PORT=2135
            - GRPC_PORT=2136
            - MON_PORT=8765
        volumes:
            - ../ydb_certs:/ydb_certs
            - ../ydb_data:/ydb_data

volumes:
    ydb_certs:
    ydb_data:
